# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x2f96f5fD967577f52f0110Da468Cf52527Bd92Fa"
    chainName: arbitrumsepolia
    decimals: 18
    name: Ethereum
    standard: EvmHypNative
    symbol: ETH
    connections:
      - token: ethereum|tontest1|EQDenKZFbm2SMb_lTu-MHoGs1tAjbRHpTi5MSuYVyeaGC6nT
  - addressOrDenom: "EQDenKZFbm2SMb_lTu-MHoGs1tAjbRHpTi5MSuYVyeaGC6nT"
    chainName: tontest1
    decimals: 18
    name: Wrapped Ether
    standard: EvmHypSynthetic
    symbol: WETH
    connections:
      - token: ethereum|tontest1|EQDenKZFbm2SMb_lTu-MHoGs1tAjbRHpTi5MSuYVyeaGC6nT
