# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x31c7eF086cbD1B089aABa7352aCAefebA0646AA2"
    chainName: arbitrumsepolia
    decimals: 18
    name: Ethereum
    standard: EvmHypNative
    symbol: ETH
    connections:
      - token: ethereum|tontest1|EQDenKZFbm2SMb_lTu-MHoGs1tAjbRHpTi5MSuYVyeaGC6nT
  - addressOrDenom: "EQBI64bUq0wXiQ5goJP1CLzBNN985ThHFxw89rOc0mJPFavB"
    chainName: tontest1
    decimals: 18
    name: Ethereum
    standard: EvmHypNative
    symbol: ETH
    connections:
      - token: ethereum|tontest1|EQDenKZFbm2SMb_lTu-MHoGs1tAjbRHpTi5MSuYVyeaGC6nT
